// frontend-consulta/src/app/pages/doctor/agenda/doctor-agenda.component.ts
import { Component } from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

function todayChile(): string {
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Santiago' }).format(new Date());
}

@Component({
  selector: 'app-doctor-agenda',
  standalone: true,
  imports: [NgIf, NgFor, FormsModule],
  templateUrl: './doctor-agenda.component.html',
})
export class DoctorAgendaComponent {
  fecha = todayChile();
  agenda: any[] = [];
  loading = false;

  constructor(private router: Router, private api: ApiService) {
    this.buscar();
  }

  volver() {
    this.router.navigateByUrl('/doctor/panel');
  }

  async buscar() {
    if (!this.fecha) return;

    this.loading = true;
    try {
      this.agenda = await firstValueFrom(this.api.agendaDoctor(this.fecha));
    } catch {
      alert('No se pudo cargar la agenda.');
      this.agenda = [];
    } finally {
      this.loading = false;
    }
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" class="text-stone-600 hover:text-stone-900 mb-4" type="button">← Volver</button>

  <h1 class="text-3xl font-semibold text-stone-900 mb-6">📅 Agenda</h1>

  <div class="bg-white border border-amber-100 rounded-3xl p-6 max-w-xl space-y-4 mb-6">
    <label class="font-semibold block">Fecha</label>
    <input type="date" [(ngModel)]="fecha" name="fecha" class="w-full px-4 py-2 border rounded-xl" />
    <button (click)="buscar()" class="w-full py-3 rounded-xl bg-stone-900 text-white font-semibold" type="button">
      Consultar
    </button>
  </div>

  <div class="bg-white border border-amber-100 rounded-3xl p-6 max-w-3xl mx-auto">
    <p *ngIf="loading" class="text-stone-600">Cargando...</p>

    <p *ngIf="!loading && agenda.length===0" class="text-stone-600">
      No hay citas para esta fecha.
    </p>

    <div *ngIf="!loading" class="space-y-3">
      <div *ngFor="let c of agenda" class="p-4 rounded-xl bg-amber-50/40 border border-amber-100">
        <p class="font-semibold text-stone-900">{{ c.paciente }}</p>
        <p>Hora: {{ c.hora_inicio }}</p>
        <p class="text-stone-600 text-sm">Estado: {{ c.estado }}</p>
      </div>
    </div>
  </div>
</div>

// clinica-react/src/pages/doctor/DoctorAgenda.jsx
import { useEffect, useState } from "react";
import { ArrowLeft, Calendar } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API_BASE = "http://127.0.0.1:8000";

const getTodayYmdChile = () =>
  new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Santiago",
  }).format(new Date());

const DoctorAgenda = () => {
  const navigate = useNavigate();
  const [agenda, setAgenda] = useState([]);
  const [loading, setLoading] = useState(false);

  const [fecha] = useState(getTodayYmdChile());

  const fetchAgenda = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API_BASE}/horas-ocupadas/?fecha=${fecha}`);
      if (!res.ok) throw new Error("Error HTTP");
      const data = await res.json();

      const ocupadas = (data.ocupadas || []).map((h, idx) => ({
        id: idx + 1,
        hora: String(h).slice(0, 5), // de "10:30:00" a "10:30"
      }));

      setAgenda(ocupadas);
    } catch (e) {
      console.error("Error cargando agenda:", e);
      alert("No se pudo cargar la agenda de hoy.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAgenda();
  }, [fecha]);

  const fechaLegible = new Date(fecha).toLocaleDateString("es-CL");

  return (
    <div className="min-h-screen bg-amber-50/60 p-6">
      <button
        onClick={() => navigate("/doctor/panel")}
        className="flex items-center gap-2 text-stone-600 hover:text-stone-900 mb-6"
      >
        <ArrowLeft size={20} /> Volver
      </button>

      <h1 className="text-3xl font-semibold text-stone-900 mb-2 flex items-center gap-2">
        <Calendar className="text-amber-700" /> Agenda de Hoy
      </h1>
      <p className="text-stone-500 mb-6">Fecha: {fechaLegible}</p>

      <div className="bg-white rounded-2xl shadow p-6 border border-amber-100">
        {loading ? (
          <p className="text-stone-500">Cargando agenda...</p>
        ) : agenda.length === 0 ? (
          <p className="text-stone-500">
            No hay citas programadas para hoy.
          </p>
        ) : (
          <div className="space-y-4">
            {agenda.map((cita) => (
              <div
                key={cita.id}
                className="p-4 rounded-xl bg-amber-50/40 border border-amber-100 flex justify-between items-center"
              >
                <div>
                  <p className="font-semibold text-stone-900 text-lg">
                    {cita.hora} hrs
                  </p>
                  <p className="text-stone-600 text-sm">
                    Cita reservada
                    {" (datos de paciente se pueden agregar más adelante)"}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default DoctorAgenda;
