// frontend-consulta/src/app/pages/doctor/pacientes/doctor-pacientes.component.ts
import { Component, OnInit } from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-doctor-pacientes',
  standalone: true,
  imports: [NgIf, NgFor, FormsModule],
  templateUrl: './doctor-pacientes.component.html',
})
export class DoctorPacientesComponent implements OnInit {
  pacientes: any[] = [];
  search = '';
  loading = false;

  constructor(private router: Router, private api: ApiService) {}

  ngOnInit() {
    this.cargar();
  }

  volver() {
    this.router.navigateByUrl('/doctor/panel');
  }

  async cargar() {
    this.loading = true;
    try {
      this.pacientes = await firstValueFrom(this.api.pacientes());
    } catch {
      alert('No se pudieron cargar pacientes.');
      this.pacientes = [];
    } finally {
      this.loading = false;
    }
  }

  get filtered() {
    const s = this.search.toLowerCase();
    return this.pacientes.filter((p) =>
      `${p.nombre} ${p.apellido}`.toLowerCase().includes(s)
    );
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" class="text-stone-600 hover:text-stone-900 mb-4" type="button">← Volver</button>

  <h1 class="text-3xl font-semibold text-stone-900 mb-6">👥 Pacientes</h1>

  <div class="flex items-center border border-amber-200 rounded-xl bg-white px-4 py-2 mb-6 max-w-xl">
    <span class="text-stone-600">🔎</span>
    <input [(ngModel)]="search" class="w-full ml-3 bg-transparent focus:outline-none" placeholder="Buscar..." />
  </div>

  <div class="bg-white border border-amber-100 rounded-3xl p-6">
    <p *ngIf="loading" class="text-stone-600">Cargando...</p>

    <p *ngIf="!loading && filtered.length===0" class="text-stone-600">No hay pacientes.</p>

    <div *ngIf="!loading" class="space-y-3">
      <div *ngFor="let p of filtered" class="p-4 rounded-xl bg-amber-50/40 border border-amber-100">
        <p class="font-semibold text-stone-900">{{ p.nombre }} {{ p.apellido }}</p>
        <p class="text-stone-700 text-sm">RUT: {{ p.rut }}</p>
        <p class="text-stone-700 text-sm">Tel: {{ p.telefono }}</p>
        <p class="text-stone-700 text-sm">Email: {{ p.email }}</p>
      </div>
    </div>
  </div>
</div>

// clinica-react/src/pages/doctor/DoctorPacientes.jsx
import { useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API_BASE = "http://127.0.0.1:8000";

const DoctorPacientes = () => {
  const navigate = useNavigate();

  const [busqueda, setBusqueda] = useState("");
  const [pacientes, setPacientes] = useState([]);
  const [cargando, setCargando] = useState(false);

  const fetchPacientes = async () => {
    setCargando(true);
    try {
      const res = await fetch(`${API_BASE}/pacientes/`);
      if (!res.ok) throw new Error("Error HTTP");
      const data = await res.json();
      setPacientes(data || []);
    } catch (e) {
      console.error("Error cargando pacientes:", e);
      alert("No se pudieron cargar los pacientes desde el servidor.");
    } finally {
      setCargando(false);
    }
  };

  useEffect(() => {
    fetchPacientes();
  }, []);

  const pacientesFiltrados = pacientes.filter((p) =>
    `${p.nombre} ${p.apellido}`.toLowerCase().includes(busqueda.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-amber-50 p-6 flex justify-center">
      <div className="w-full max-w-5xl space-y-8">
        {/* Volver */}
        <button
          onClick={() => navigate("/doctor/panel")}
          className="flex items-center gap-2 text-stone-600 hover:text-stone-900 mb-6"
        >
          <ArrowLeft size={20} /> Volver
        </button>

        {/* Título */}
        <h1 className="text-3xl font-bold text-stone-900">
          Pacientes Registrados
        </h1>

        {/* Contenedor */}
        <section className="bg-white rounded-3xl border border-stone-200 shadow-sm p-6">
          {/* Buscador */}
          <input
            type="text"
            placeholder="Buscar paciente por nombre."
            className="w-full px-4 py-2 border border-stone-300 rounded-xl mb-4"
            value={busqueda}
            onChange={(e) => setBusqueda(e.target.value)}
          />

          {/* Tabla */}
          <div className="overflow-hidden rounded-2xl border border-stone-200">
            <table className="w-full text-left text-sm">
              <thead className="bg-amber-50">
                <tr>
                  <th className="px-4 py-3 font-semibold">Nombre</th>
                  <th className="px-4 py-3 font-semibold">RUT</th>
                  <th className="px-4 py-3 font-semibold">Teléfono</th>
                  <th className="px-4 py-3 font-semibold">Email</th>
                </tr>
              </thead>

              <tbody>
                {cargando && (
                  <tr>
                    <td
                      colSpan="4"
                      className="px-4 py-6 text-center text-stone-500"
                    >
                      Cargando pacientes...
                    </td>
                  </tr>
                )}

                {!cargando && pacientesFiltrados.length === 0 && (
                  <tr>
                    <td
                      colSpan="4"
                      className="px-4 py-6 text-center text-stone-500"
                    >
                      No se encontraron pacientes.
                    </td>
                  </tr>
                )}

                {!cargando &&
                  pacientesFiltrados.map((paciente, idx) => (
                    <tr key={idx} className="border-t">
                      <td className="px-4 py-3">
                        {paciente.nombre} {paciente.apellido}
                      </td>
                      <td className="px-4 py-3">{paciente.rut}</td>
                      <td className="px-4 py-3">{paciente.telefono}</td>
                      <td className="px-4 py-3">{paciente.email}</td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
        </section>
      </div>
    </div>
  );
};

export default DoctorPacientes;
