// frontend-consulta/src/app/pages/doctor/panel/doctor-panel.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-doctor-panel',
  standalone: true,
  templateUrl: './doctor-panel.component.html',
})
export class DoctorPanelComponent {
  nombre = localStorage.getItem('userName') || '';
  apellido = localStorage.getItem('userApellido') || '';

  constructor(private router: Router) {}

  logout() {
    localStorage.clear();
    this.router.navigateByUrl('/');
  }

  go(path: string) {
    this.router.navigateByUrl(path);
  }
}

<main class="min-h-screen bg-amber-50/40 px-6 py-8">
  <div class="flex justify-end mb-6">
    <button
      (click)="logout()"
      class="flex items-center gap-2 px-4 py-2 rounded-lg border border-stone-300 text-stone-700 hover:bg-stone-200 transition"
      type="button"
    >
      ⎋ Cerrar Sesión
    </button>
  </div>

  <h1 class="text-3xl font-semibold text-stone-900">
    Buenos días, Dr. {{ nombre }} {{ apellido }}
  </h1>
  <p class="text-stone-500 mb-10">Panel médico</p>

  <section class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <button (click)="go('/doctor/agenda')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">📅</div>
      <div class="font-semibold text-stone-900">Agenda</div>
      <div class="text-stone-600 text-sm mt-1">Revisar citas por fecha</div>
      <div class="mt-4 font-semibold text-stone-900">Ver →</div>
    </button>

    <button (click)="go('/doctor/fichas')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">📄</div>
      <div class="font-semibold text-stone-900">Fichas</div>
      <div class="text-stone-600 text-sm mt-1">Ver historial y crear fichas</div>
      <div class="mt-4 font-semibold text-stone-900">Ver →</div>
    </button>

    <button (click)="go('/doctor/pacientes')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">👥</div>
      <div class="font-semibold text-stone-900">Pacientes</div>
      <div class="text-stone-600 text-sm mt-1">Listar pacientes registrados</div>
      <div class="mt-4 font-semibold text-stone-900">Ver →</div>
    </button>
  </section>
</main>

// clinica-react/src/pages/doctor/DoctorPanel.jsx
import { useNavigate } from "react-router-dom";
import { Calendar, FileText, Users, LogOut } from "lucide-react";
import DashboardCard from "../../components/common/DashboardCard";

const DoctorPanel = () => {
  const navigate = useNavigate();

  const nombre = localStorage.getItem("userName") || "";
  const apellido = localStorage.getItem("userApellido") || "";

  const handleLogout = () => {
    localStorage.clear();
    navigate("/");
  };

  return (
    <main className="min-h-screen bg-amber-50/40 px-6 py-8">
      {/* Logout arriba derecha */}
      <div className="flex justify-end mb-6">
        <button
          onClick={handleLogout}
          className="flex items-center gap-2 px-4 py-2 rounded-lg border border-stone-300 text-stone-700 hover:bg-stone-200 transition"
        >
          <LogOut size={18} />
          Cerrar Sesión
        </button>
      </div>

      {/* Bienvenida */}
      <h1 className="text-3xl font-semibold text-stone-900">
        Buenos días, Dr. {nombre} {apellido}
      </h1>
      <p className="text-stone-500 mb-10">Panel de Gestión Médica</p>

      {/* Tarjetas del panel */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <DashboardCard
          Icon={Calendar}
          title="Agenda"
          subtitle="Revisar tus citas del día"
          buttonText="Ver Agenda"
          to="/doctor/agenda"
        />

        <DashboardCard
          Icon={FileText}
          title="Fichas Médicas"
          subtitle="Gestionar y revisar fichas"
          buttonText="Ver Fichas"
          to="/doctor/fichas"
        />

        <DashboardCard
          Icon={Users}
          title="Pacientes"
          subtitle="Información y búsqueda de pacientes"
          buttonText="Ver Pacientes"
          to="/doctor/pacientes"
        />
      </section>
    </main>
  );
};

export default DoctorPanel;
