// frontend-consulta/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api';
import { AuthService } from '../../services/auth.service';
import { firstValueFrom } from 'rxjs';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule,CommonModule],
  templateUrl: './register.component.html',
})
export class RegisterComponent {
  form = { nombre: '', apellido: '', rut: '', email: '', password: '', confirm: '' };
  error = '';
  loading = false;

  constructor(private router: Router, private api: ApiService, private auth: AuthService) {}

  async submit(e: Event) {
    e.preventDefault();
    if (this.form.password !== this.form.confirm) {
      this.error = 'Las contraseñas no coinciden.';
      return;
    }

    this.loading = true;
    this.error = '';
    try {
      const data = await firstValueFrom(this.api.register({
        nombre: this.form.nombre,
        apellido: this.form.apellido,
        rut: this.form.rut,
        email: this.form.email,
        password: this.form.password,
      }));
      this.auth.setRegisterData(data);
      this.router.navigateByUrl('/login');
    } catch (err: any) {
      this.error = err?.error?.detail ?? 'No se pudo registrar.';
    } finally {
      this.loading = false;
    }
  }

  goLogin() { this.router.navigateByUrl('/login'); }
  goHome() { this.router.navigateByUrl('/'); }
}

<div class="min-h-screen bg-amber-50/80 flex items-center justify-center px-4">
  <div class="w-full max-w-md bg-white rounded-3xl border border-amber-100 p-8">
    <button (click)="goHome()" class="text-sm text-stone-600 mb-4" type="button">← Volver</button>

    <h1 class="text-2xl font-semibold text-stone-900 text-center mb-2">Crear Cuenta</h1>

    <div *ngIf="error" class="mb-4 text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-3 py-2">
      {{ error }}
    </div>

    <form (submit)="submit($event)" class="space-y-4">
      <input name="nombre" [(ngModel)]="form.nombre" placeholder="Nombre" class="w-full px-4 py-2 border rounded-xl" />
      <input name="apellido" [(ngModel)]="form.apellido" placeholder="Apellido" class="w-full px-4 py-2 border rounded-xl" />
      <input name="rut" [(ngModel)]="form.rut" placeholder="RUT" class="w-full px-4 py-2 border rounded-xl" />
      <input name="email" [(ngModel)]="form.email" placeholder="Email" class="w-full px-4 py-2 border rounded-xl" />
      <input type="password" name="password" [(ngModel)]="form.password" placeholder="Contraseña" class="w-full px-4 py-2 border rounded-xl" />
      <input type="password" name="confirm" [(ngModel)]="form.confirm" placeholder="Confirmar contraseña" class="w-full px-4 py-2 border rounded-xl" />

      <button type="submit" [disabled]="loading"
        class="w-full py-3 rounded-xl bg-stone-900 text-white font-semibold disabled:opacity-60">
        {{ loading ? 'Registrando...' : 'Registrar' }}
      </button>
    </form>

    <p class="text-center text-sm text-stone-600 mt-4">
      ¿Ya tienes cuenta?
      <button (click)="goLogin()" class="font-semibold text-stone-900" type="button">Inicia sesión</button>
    </p>
  </div>
</div>

// clinica-react/src/pages/Register.jsx
import { useState } from "react";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const Register = () => {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    nombre: "",
    apellido: "",
    rut: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
    setError("");
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (form.password !== form.confirmPassword) {
      setError("Las contraseñas no coinciden.");
      return;
    }

    try {
      setLoading(true);
      setError("");

      const res = await fetch("http://127.0.0.1:8000/registro/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          nombre: form.nombre,
          apellido: form.apellido,
          rut: form.rut,
          email: form.email,
          password: form.password,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.detail || "Error al registrar el usuario.");
        return;
      }

      // Guardamos datos del usuario
      localStorage.setItem("idUsuario", data.idUsuario);
      localStorage.setItem("userRut", data.rut);
      localStorage.setItem("pacienteId", data.pacienteId ?? "");
      localStorage.setItem("userName", data.nombre);
      localStorage.setItem("userApellido", data.apellido);
      localStorage.setItem("userEmail", data.email);

      // Después de registrarse lo enviamos al login
      navigate("/login");

    } catch (err) {
      console.error(err);
      setError("No se pudo conectar con el servidor.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-amber-50/80 flex items-center justify-center px-4">
      <div className="w-full max-w-md bg-white rounded-3xl shadow-lg border border-amber-100 p-8">

        {/* Volver al home */}
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-sm text-stone-600 hover:text-stone-900 mb-4"
        >
          <ArrowLeft size={18} /> Volver al inicio
        </button>

        <h1 className="text-2xl md:text-3xl font-semibold text-stone-900 text-center mb-2">
          Crear Cuenta
        </h1>
        <p className="text-center text-stone-500 mb-6 text-sm">
          Regístrate para acceder a tu portal médico personal.
        </p>

        {error && (
          <div className="mb-4 text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-3 py-2">
            {error}
          </div>
        )}

        <form className="space-y-4" onSubmit={handleSubmit}>
          {/* Nombre */}
          <div>
            <label className="block text-sm font-medium text-stone-800 mb-1">
              Nombre
            </label>
            <input
              name="nombre"
              value={form.nombre}
              onChange={handleChange}
              className="w-full px-4 py-2 rounded-xl border border-stone-300 focus:ring-2 focus:ring-amber-500"
              placeholder="Ingrese nombre"
            />
          </div>

          {/* Apellido */}
          <div>
            <label className="block text-sm font-medium text-stone-800 mb-1">
              Apellido
            </label>
            <input
              name="apellido"
              value={form.apellido}
              onChange={handleChange}
              className="w-full px-4 py-2 rounded-xl border border-stone-300 focus:ring-2 focus:ring-amber-500"
              placeholder="Ingrese apellido"
            />
          </div>

          {/* RUT */}
          <div>
            <label className="block text-sm font-medium text-stone-800 mb-1">
              RUT
            </label>
            <input
              name="rut"
              value={form.rut}
              onChange={handleChange}
              className="w-full px-4 py-2 rounded-xl border border-stone-300 focus:ring-2 focus:ring-amber-500"
              placeholder="11.111.111-1"
            />
          </div>

          {/* Email */}
          <div>
            <label className="block text-sm font-medium text-stone-800 mb-1">
              Email
            </label>
            <input
              type="email"
              name="email"
              value={form.email}
              onChange={handleChange}
              className="w-full px-4 py-2 rounded-xl border border-stone-300 focus:ring-2 focus:ring-amber-500"
              placeholder="correo@ejemplo.com"
            />
          </div>

          {/* Password */}
          <div>
            <label className="block text-sm font-medium text-stone-800 mb-1">
              Contraseña
            </label>
            <input
              type="password"
              name="password"
              value={form.password}
              onChange={handleChange}
              className="w-full px-4 py-2 rounded-xl border border-stone-300 focus:ring-2 focus:ring-amber-500"
              placeholder="*******"
            />
          </div>

          {/* Confirm Password */}
          <div>
            <label className="block text-sm font-medium text-stone-800 mb-1">
              Confirmar Contraseña
            </label>
            <input
              type="password"
              name="confirmPassword"
              value={form.confirmPassword}
              onChange={handleChange}
              className="w-full px-4 py-2 rounded-xl border border-stone-300 focus:ring-2 focus:ring-amber-500"
              placeholder="*******"
            />
          </div>

          {/* Submit */}
          <button
            type="submit"
            disabled={loading}
            className="w-full mt-4 py-3 rounded-xl bg-stone-900 text-white font-semibold hover:bg-stone-800 transition disabled:opacity-70"
          >
            {loading ? "Registrando..." : "Registrarse"}
          </button>
        </form>

        <p className="text-center text-sm text-stone-600 mt-4">
          ¿Ya tienes una cuenta?{" "}
          <button
            type="button"
            onClick={() => navigate("/login")}
            className="font-semibold text-stone-900 hover:underline"
          >
            Inicia sesión aquí
          </button>
        </p>
      </div>
    </div>
  );
};

export default Register;
