// clinica-react/src/pages/secretaria/SecretariaAgendarHora.jsx
import { useState, useEffect } from "react";
import { ArrowLeft, Search } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Button from "../../components/common/Button";

const API = "http://127.0.0.1:8000";

const generarBloques30 = (inicio, fin, fechaStr) => {
  const bloques = [];
  let hora = new Date(inicio);

  while (hora < fin) {
    bloques.push(hora.toTimeString().slice(0, 5));
    hora = new Date(hora.getTime() + 30 * 60000);
  }
  return bloques;
};

const generarHoras = (fechaStr) => {
  const d = new Date(`${fechaStr}T00:00`);
  const dia = d.getDay();

  if (dia === 0 || dia === 6) return [];
  if (dia >= 1 && dia <= 4)
    return [
      ...generarBloques30(new Date(`${fechaStr}T10:30`), new Date(`${fechaStr}T13:00`)),
      ...generarBloques30(new Date(`${fechaStr}T15:00`), new Date(`${fechaStr}T19:00`)),
    ];
  if (dia === 5)
    return generarBloques30(new Date(`${fechaStr}T10:30`), new Date(`${fechaStr}T13:00`));
};

const SecretariaAgendarHora = () => {
  const navigate = useNavigate();

  const [rut, setRut] = useState("");
  const [paciente, setPaciente] = useState(null);

  const [fecha, setFecha] = useState("");
  const [horasDisponibles, setHorasDisponibles] = useState([]);
  const [horaSeleccionada, setHoraSeleccionada] = useState("");

  const buscarPaciente = async () => {
    try {
      const res = await fetch(`${API}/pacientes/${rut}/`);
      if (!res.ok) {
        setPaciente(null);
        alert("Paciente no encontrado");
        return;
      }
      setPaciente(await res.json());
    } catch {
      alert("Error buscando paciente");
    }
  };

  useEffect(() => {
    const cargar = async () => {
      if (!fecha) return;

      const bloques = generarHoras(fecha);
      if (!bloques) return;

      const res = await fetch(`${API}/horas/agenda-doctor/?fecha=${fecha}`);
      const ocupadas = await res.json();

      const disponibles = bloques.filter(
        (b) => !ocupadas.some((o) => o.hora_inicio.startsWith(b))
      );

      setHorasDisponibles(disponibles);
    };

    cargar();
  }, [fecha]);

  const calcularHoraFinal = (horaInicio) => {
  const [h, m] = horaInicio.split(":").map(Number);
  const d = new Date();
  d.setHours(h, m + 30);
  return d.toTimeString().slice(0, 5);
};


  const guardarCita = async () => {
  if (!paciente || !fecha || !horaSeleccionada) {
    alert("Debe completar todos los campos");
    return;
  }

  const payload = {
    paciente_id: paciente.id_paciente,
    fecha,
    hora_inicio: horaSeleccionada,
    hora_final: calcularHoraFinal(horaSeleccionada),
  };

  const res = await fetch(`${API}/horas/agendar/`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  const data = await res.json();

  if (!res.ok) {
    alert(data.detail || "Error al guardar cita");
    return;
  }

  alert("Cita agendada correctamente");
  navigate("/secretaria/agenda-doctor");
};



  return (
    <div className="min-h-screen bg-amber-50/60 p-6">

      <button
        onClick={() => navigate("/secretaria/panel")}
        className="flex items-center gap-2 text-stone-600 hover:text-stone-900 mb-6"
      >
        <ArrowLeft size={20} /> Volver
      </button>

      <div className="bg-white p-8 rounded-3xl border border-amber-100 max-w-3xl mx-auto">

        <h1 className="text-3xl font-semibold text-stone-900 mb-6">
          Agendar Hora Médica
        </h1>

        <label>Buscar paciente por RUT:</label>
        <div className="flex gap-2 mb-6">
          <input
            value={rut}
            onChange={(e) => setRut(e.target.value)}
            className="flex-1 px-4 py-2 border rounded-lg"
          />
          <Button variant="secondary" onClick={buscarPaciente}>
            <Search size={16} className="inline mr-1" />
            Buscar
          </Button>
        </div>

        {paciente && (
            <div className="bg-amber-50/40 p-4 rounded-xl mb-6 border border-amber-100 text-sm">
              <p className="font-semibold">
              {paciente.nombre} {paciente.apellido}
              </p>
              <p><strong>RUT:</strong> {paciente.rut}</p>
              <p><strong>Teléfono:</strong> {paciente.telefono}</p>
              <p><strong>Dirección:</strong> {paciente.direccion}</p>
              <p><strong>Previsión:</strong> {paciente.prevision}</p>
              <p><strong>Email:</strong> {paciente.email}</p>
        </div>
      )}

        <label>Fecha:</label>
        <input
          type="date"
          min={new Date().toISOString().split("T")[0]}
          value={fecha}
          onChange={(e) => setFecha(e.target.value)}
          className="w-full px-4 py-2 border rounded-lg mb-6"
        />

        {fecha && (
          <>
            <h2 className="font-semibold mb-3">Horas Disponibles</h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-6">
              {horasDisponibles.map((h) => (
                <button
                  key={h}
                  className={`px-4 py-2 rounded-lg border ${
                    horaSeleccionada === h
                      ? "bg-amber-600 text-white"
                      : "bg-white text-stone-800 border-amber-200 hover:bg-amber-100"
                  }`}
                  onClick={() => setHoraSeleccionada(h)}
                >
                  {h}
                </button>
              ))}
            </div>
          </>
        )}

        <Button variant="primary" className="w-full" onClick={guardarCita}>
          Guardar Cita
        </Button>
      </div>
    </div>
  );
};

export default SecretariaAgendarHora;

// frontend-consulta/src/app/pages/secretaria/agendar/secretaria-agendar-hora.component.ts
import { Component } from '@angular/core';
import { NgIf, NgFor, NgClass } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-secretaria-agendar-hora',
  standalone: true,
  imports: [NgIf, NgFor, NgClass, FormsModule],
  templateUrl: './secretaria-agendar-hora.component.html',
})
export class SecretariaAgendarHoraComponent {
  rut = '';
  paciente: any = null;

  fecha = '';
  horasDisponibles: string[] = [];
  horaSeleccionada = '';

  constructor(private router: Router, private api: ApiService) {}

  volver() {
    this.router.navigateByUrl('/secretaria/panel');
  }

  minDate(): string {
    return new Date().toISOString().split('T')[0];
  }

  private bloques30(inicio: Date, fin: Date): string[] {
    const out: string[] = [];
    let t = new Date(inicio);
    while (t < fin) {
      out.push(t.toTimeString().slice(0, 5));
      t = new Date(t.getTime() + 30 * 60000);
    }
    return out;
  }

  private generarHoras(fechaStr: string): string[] {
    const d = new Date(`${fechaStr}T00:00`);
    const dia = d.getDay(); // 0 dom ... 6 sáb

    if (dia === 0 || dia === 6) return [];

    if (dia >= 1 && dia <= 4) {
      return [
        ...this.bloques30(new Date(`${fechaStr}T10:30`), new Date(`${fechaStr}T13:00`)),
        ...this.bloques30(new Date(`${fechaStr}T15:00`), new Date(`${fechaStr}T19:00`)),
      ];
    }

    // viernes
    return this.bloques30(new Date(`${fechaStr}T10:30`), new Date(`${fechaStr}T13:00`));
  }

  horaFinal(h: string): string {
    const [hh, mm] = h.split(':').map(Number);
    const d = new Date();
    d.setHours(hh, mm + 30, 0, 0);
    return d.toTimeString().slice(0, 5);
  }

  async buscarPaciente() {
    try {
      this.paciente = await firstValueFrom(this.api.pacientePorRut(this.rut));
      alert('Paciente encontrado');
    } catch {
      this.paciente = null;
      alert('Paciente no encontrado');
    }
  }

  async changeFecha(v: string) {
    this.fecha = v;
    this.horaSeleccionada = '';
    await this.cargarHoras();
  }

  async cargarHoras() {
    if (!this.fecha) return;

    const bloques = this.generarHoras(this.fecha);
    if (bloques.length === 0) {
      this.horasDisponibles = [];
      return;
    }

    try {
      const agenda = await firstValueFrom(this.api.agendaDoctor(this.fecha));

      const disponibles = bloques.filter((b) => {
        return !(agenda ?? []).some((c: any) => String(c.hora_inicio ?? '').startsWith(b));
      });

      this.horasDisponibles = disponibles;
    } catch {
      // si falla la agenda, al menos mostramos bloques
      this.horasDisponibles = bloques;
    }
  }

  async guardarCita() {
    if (!this.paciente || !this.fecha || !this.horaSeleccionada) {
      return alert('Debe completar todos los campos');
    }

    try {
      await firstValueFrom(this.api.agendarHora({
        paciente_id: this.paciente.id_paciente,
        fecha: this.fecha,
        hora_inicio: this.horaSeleccionada,
        hora_final: this.horaFinal(this.horaSeleccionada),
      }));

      alert('Cita agendada correctamente');
      this.router.navigateByUrl('/secretaria/agenda-doctor');
    } catch (err: any) {
      alert(err?.error?.detail ?? 'Error al agendar cita');
    }
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" class="text-stone-600 hover:text-stone-900 mb-4" type="button">← Volver</button>

  <div class="bg-white border border-amber-100 rounded-3xl p-8 max-w-3xl mx-auto space-y-5">
    <h1 class="text-3xl font-semibold text-stone-900">Agendar Hora (Secretaría)</h1>

    <div>
      <label class="font-semibold block mb-1">RUT paciente</label>
      <div class="flex gap-2">
        <input [(ngModel)]="rut" name="rut" class="flex-1 px-4 py-2 border rounded-xl" placeholder="11.111.111-1" />
        <button (click)="buscarPaciente()" class="px-4 py-2 border rounded-xl" type="button">Buscar</button>
      </div>
    </div>

    <div *ngIf="paciente" class="bg-amber-50/40 border border-amber-100 rounded-xl p-4 text-sm">
      <p class="font-semibold">{{ paciente.nombre }} {{ paciente.apellido }}</p>
      <p>RUT: {{ paciente.rut }}</p>
      <p>Tel: {{ paciente.telefono }}</p>
      <p>Dirección: {{ paciente.direccion }}</p>
      <p>Previsión: {{ paciente.prevision }}</p>
      <p>Email: {{ paciente.email }}</p>
    </div>

    <div>
      <label class="font-semibold block mb-1">Fecha</label>
      <input type="date" [min]="minDate()" [value]="fecha"
        (change)="changeFecha($any($event.target).value)"
        class="px-4 py-2 border rounded-xl" />
    </div>

    <div *ngIf="fecha">
      <h2 class="font-semibold mb-2">Horas Disponibles</h2>

      <p *ngIf="horasDisponibles.length===0" class="text-stone-600">
        No hay horas disponibles para esta fecha.
      </p>

      <div class="grid grid-cols-2 sm:grid-cols-3 gap-3">
        <button *ngFor="let h of horasDisponibles"
          (click)="horaSeleccionada=h"
          class="py-2 rounded-lg border"
          [ngClass]="horaSeleccionada===h ? 'bg-amber-600 text-white' : 'bg-white'"
          type="button">
          {{ h }}
        </button>
      </div>
    </div>

    <button (click)="guardarCita()"
      class="w-full py-3 rounded-xl bg-stone-900 text-white font-semibold"
      type="button">
      Guardar Cita
    </button>
  </div>
</div>
