// clinica-react/src/pages/secretaria/SecretariaAgendaDoctor.jsx
import { useState } from "react";
import { ArrowLeft, Calendar } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API = "http://127.0.0.1:8000";

const SecretariaAgendaDoctor = () => {
  const navigate = useNavigate();

  const [fecha, setFecha] = useState("");
  const [agenda, setAgenda] = useState([]);

  const buscarAgenda = async () => {
    if (!fecha) return;

    const res = await fetch(`${API}/horas/agenda-doctor/?fecha=${fecha}`);
    const data = await res.json();
    setAgenda(data);
  };

  return (
    <div className="min-h-screen bg-amber-50/60 p-6">
      
      <button
        onClick={() => navigate("/secretaria/panel")}
        className="flex items-center gap-2 text-stone-600 hover:text-stone-900 mb-6"
      >
        <ArrowLeft size={20} /> Volver
      </button>

      <h1 className="text-3xl font-semibold flex items-center gap-2 mb-6">
        <Calendar className="text-amber-700" /> Agenda del Doctor
      </h1>

      <div className="bg-white p-6 rounded-3xl border border-amber-100 max-w-xl mb-6 space-y-4">
        <label className="font-semibold">Fecha:</label>

        <input
          type="date"
          className="w-full px-4 py-2 border rounded-lg"
          value={fecha}
          onChange={(e) => setFecha(e.target.value)}
        />

        <button
          onClick={buscarAgenda}
          className="w-full bg-stone-900 text-white py-3 rounded-lg font-semibold hover:bg-stone-800"
        >
          Consultar Agenda
        </button>
      </div>

      <div className="bg-white p-6 rounded-3xl border border-amber-100 max-w-3xl mx-auto">
        {agenda.length === 0 ? (
          <p className="text-stone-600">No hay citas en esta fecha.</p>
        ) : (
          agenda.map((c, i) => (
            <div
              key={i}
              className="p-4 bg-amber-50/40 border border-amber-100 rounded-xl mb-4"
            >
              <p className="font-semibold text-stone-900">{c.paciente}</p>
              <p>Hora: {c.hora_inicio}</p>
              <p className="text-stone-600 text-sm">Estado: {c.estado}</p>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default SecretariaAgendaDoctor;

// frontend-consulta/src/app/pages/secretaria/agenda-doctor/secretaria-agenda-doctor.component.ts
import { Component } from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-secretaria-agenda-doctor',
  standalone: true,
  imports: [NgIf, NgFor, FormsModule],
  templateUrl: './secretaria-agenda-doctor.component.html',
})
export class SecretariaAgendaDoctorComponent {
  fecha = '';
  agenda: any[] = [];

  constructor(private router: Router, private api: ApiService) {}

  volver() {
    this.router.navigateByUrl('/secretaria/panel');
  }

  async buscar() {
    if (!this.fecha) return;

    try {
      this.agenda = await firstValueFrom(this.api.agendaDoctor(this.fecha));
    } catch {
      alert('No se pudo cargar la agenda.');
      this.agenda = [];
    }
  }

  async cancelar(idHora: number) {
    if (!confirm('¿Cancelar esta hora?')) return;

    try {
      await firstValueFrom(this.api.cancelarHora(idHora));
      alert('Hora cancelada');
      await this.buscar();
    } catch {
      alert('No se pudo cancelar');
    }
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" class="text-stone-600 hover:text-stone-900 mb-4" type="button">← Volver</button>

  <h1 class="text-3xl font-semibold text-stone-900 mb-6">🗓️ Agenda del Doctor</h1>

  <div class="bg-white border border-amber-100 rounded-3xl p-6 max-w-xl space-y-4 mb-6">
    <label class="font-semibold block">Fecha</label>
    <input type="date" [(ngModel)]="fecha" name="fecha" class="w-full px-4 py-2 border rounded-xl" />
    <button (click)="buscar()" class="w-full py-3 rounded-xl bg-stone-900 text-white font-semibold" type="button">
      Consultar Agenda
    </button>
  </div>

  <div class="bg-white border border-amber-100 rounded-3xl p-6 max-w-3xl mx-auto">
    <p *ngIf="agenda.length===0" class="text-stone-600">No hay citas para esta fecha.</p>

    <div *ngFor="let c of agenda" class="p-4 rounded-xl bg-amber-50/40 border border-amber-100 mb-3 flex justify-between">
      <div>
        <p class="font-semibold text-stone-900">{{ c.paciente }}</p>
        <p>Hora: {{ c.hora_inicio }}</p>
        <p class="text-stone-600 text-sm">Estado: {{ c.estado }}</p>
      </div>

      <!-- Si tu endpoint devuelve id de la hora, úsalo aquí (c.id). Si no, quítalo. -->
      <button *ngIf="c.id" (click)="cancelar(c.id)" class="text-red-600 font-semibold" type="button">
        Cancelar
      </button>
    </div>
  </div>
</div>
