// frontend-consulta/src/app/pages/secretaria/pacientes/secretaria-pacientes.component.ts
import { Component, OnInit } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-secretaria-pacientes',
  standalone: true,
  imports: [NgFor, NgIf, FormsModule],
  templateUrl: './secretaria-pacientes.component.html',
})
export class SecretariaPacientesComponent implements OnInit {
  pacientes: any[] = [];
  search = '';

  constructor(private router: Router, private api: ApiService) {}

  ngOnInit() {
    this.cargar();
  }

  volver() {
    this.router.navigateByUrl('/secretaria/panel');
  }

  async cargar() {
    try {
      this.pacientes = await firstValueFrom(this.api.pacientes());
    } catch {
      alert('No se pudieron cargar pacientes.');
      this.pacientes = [];
    }
  }

  get filtered() {
    const s = this.search.toLowerCase();
    return this.pacientes.filter((p) =>
      `${p.nombre} ${p.apellido}`.toLowerCase().includes(s)
    );
  }

  editar(rut: string) {
    this.router.navigateByUrl(`/secretaria/pacientes/${rut}`);
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" class="text-stone-600 hover:text-stone-900 mb-4" type="button">← Volver</button>
  <h1 class="text-3xl font-semibold text-stone-900 mb-6">Pacientes</h1>

  <div class="flex items-center border border-amber-200 rounded-xl bg-white px-4 py-2 mb-6 max-w-xl">
    <span class="text-stone-600">🔎</span>
    <input [(ngModel)]="search" class="w-full ml-3 bg-transparent focus:outline-none" placeholder="Buscar paciente..." />
  </div>

  <div class="space-y-3">
    <div *ngFor="let p of filtered" class="bg-white border border-amber-100 rounded-xl p-4 flex justify-between">
      <div>
        <p class="font-semibold text-stone-900">{{ p.nombre }} {{ p.apellido }}</p>
        <p class="text-stone-600 text-sm">{{ p.email }}</p>
        <p class="text-stone-600 text-sm">RUT: {{ p.rut }}</p>
      </div>
      <button (click)="editar(p.rut)" class="text-stone-800 hover:underline" type="button">Editar</button>
    </div>

    <p *ngIf="filtered.length===0" class="text-stone-500">No hay pacientes.</p>
  </div>
</div>

// clinica-react/src/pages/secretaria/SecretariaPacientes.jsx
import { useState, useEffect } from "react";
import { ArrowLeft, Edit, Search } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API = "http://127.0.0.1:8000";

const SecretariaPacientes = () => {
  const navigate = useNavigate();

  const [pacientes, setPacientes] = useState([]);
  const [search, setSearch] = useState("");

  const cargarPacientes = async () => {
    try {
      const res = await fetch(`${API}/pacientes/`);
      const data = await res.json();
      setPacientes(data);
    } catch (error) {
      console.error("Error cargando pacientes:", error);
      alert("No se pudo cargar la lista de pacientes.");
    }
  };

  useEffect(() => {
    cargarPacientes();
  }, []);

  const filtered = pacientes.filter((p) =>
    `${p.nombre} ${p.apellido}`.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-amber-50/60 p-6">

      {/* BOTÓN VOLVER */}
      <button
        onClick={() => navigate("/secretaria/panel")}
        className="flex items-center text-stone-600 hover:text-stone-900 gap-2 mb-6"
      >
        <ArrowLeft size={20} /> Volver
      </button>

      <h1 className="text-3xl font-semibold text-stone-900 mb-6">
        Pacientes
      </h1>

      {/* BUSCADOR — diseño original */}
      <div className="flex items-center border border-amber-200 rounded-xl bg-white px-4 py-2 mb-6 max-w-xl">
        <Search size={18} className="text-stone-600" />
        <input
          placeholder="Buscar paciente..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full ml-3 bg-transparent focus:outline-none"
        />
      </div>

      {/* LISTA DE PACIENTES — diseño original */}
      <div className="space-y-4">
        {filtered.map((p) => (
          <div
            key={p.rut}
            className="bg-white p-4 rounded-xl shadow border border-amber-100 flex justify-between"
          >
            <div>
              <p className="font-semibold text-stone-900">
                {p.nombre} {p.apellido}
              </p>
              <p className="text-stone-600 text-sm">{p.email}</p>
            </div>

            <button
              onClick={() => navigate(`/secretaria/pacientes/${p.rut}`)}
              className="flex items-center gap-2 text-stone-700 hover:text-stone-900"
            >
              <Edit size={18} /> Editar
            </button>
          </div>
        ))}

        {filtered.length === 0 && (
          <p className="text-stone-500 text-center">No hay pacientes encontrados.</p>
        )}
      </div>
    </div>
  );
};

export default SecretariaPacientes;
