// frontend-consulta/src/app/pages/secretaria/panel/secretaria-panel.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-secretaria-panel',
  standalone: true,
  templateUrl: './secretaria-panel.component.html',
})
export class SecretariaPanelComponent {
  nombre = localStorage.getItem('userName') || '';
  apellido = localStorage.getItem('userApellido') || '';

  constructor(private router: Router) {}

  logout() {
    localStorage.clear();
    this.router.navigateByUrl('/');
  }

  go(path: string) {
    this.router.navigateByUrl(path);
  }
}

<main class="min-h-screen bg-amber-50/40 px-6 py-8">
  <div class="flex justify-end mb-6">
    <button
      (click)="logout()"
      class="flex items-center gap-2 px-4 py-2 rounded-lg border border-stone-300 text-stone-700 hover:bg-stone-200 transition"
      type="button"
    >
      ⎋ Cerrar Sesión
    </button>
  </div>

  <h1 class="text-3xl font-semibold text-stone-900">
    Bienvenida, {{ nombre }} {{ apellido }}
  </h1>
  <p class="text-stone-500 mb-10">Panel de Secretaría</p>

  <section class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <button (click)="go('/secretaria/agendar')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">📅</div>
      <div class="font-semibold text-stone-900">Agendar Hora</div>
      <div class="text-stone-600 text-sm mt-1">Crear citas médicas</div>
      <div class="mt-4 font-semibold text-stone-900">Agendar →</div>
    </button>

    <button (click)="go('/secretaria/pacientes')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">👥</div>
      <div class="font-semibold text-stone-900">Pacientes</div>
      <div class="text-stone-600 text-sm mt-1">Ver y editar pacientes</div>
      <div class="mt-4 font-semibold text-stone-900">Ver →</div>
    </button>

    <button (click)="go('/secretaria/registrar')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">➕</div>
      <div class="font-semibold text-stone-900">Registrar Paciente</div>
      <div class="text-stone-600 text-sm mt-1">Agregar un nuevo paciente</div>
      <div class="mt-4 font-semibold text-stone-900">Registrar →</div>
    </button>

    <button (click)="go('/secretaria/fichas')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">📄</div>
      <div class="font-semibold text-stone-900">Fichas</div>
      <div class="text-stone-600 text-sm mt-1">Ver fichas médicas</div>
      <div class="mt-4 font-semibold text-stone-900">Ver →</div>
    </button>

    <button (click)="go('/secretaria/agenda-doctor')"
      class="bg-white border border-amber-100 rounded-3xl p-6 shadow text-left hover:bg-amber-50 transition"
      type="button">
      <div class="text-2xl mb-2">🗓️</div>
      <div class="font-semibold text-stone-900">Agenda Doctor</div>
      <div class="text-stone-600 text-sm mt-1">Revisar agenda por fecha</div>
      <div class="mt-4 font-semibold text-stone-900">Ver →</div>
    </button>
  </section>
</main>

// clinica-react/src/pages/secretaria/SecretariaPanel.jsx
import { useNavigate } from "react-router-dom";
import {
  Calendar,
  Users,
  FileText,
  UserPlus,
  LogOut,
} from "lucide-react";
import DashboardCard from "../../components/common/DashboardCard";

const SecretariaPanel = () => {
  const navigate = useNavigate();

  const nombre = localStorage.getItem("userName") || "";
  const apellido = localStorage.getItem("userApellido") || "";

  const handleLogout = () => {
    localStorage.clear();
    navigate("/");
  };

  return (
    <main className="min-h-screen bg-amber-50/40 px-6 py-8">

      {/* Cerrar sesión */}
      <div className="flex justify-end mb-6">
        <button
          onClick={handleLogout}
          className="flex items-center gap-2 px-4 py-2 border border-stone-300 text-stone-700 hover:bg-stone-200 rounded-lg transition"
        >
          <LogOut size={18} />
          Cerrar Sesión
        </button>
      </div>

      {/* Bienvenida */}
      <h1 className="text-3xl font-semibold text-stone-900">
        Bienvenida, {nombre} {apellido}
      </h1>
      <p className="text-stone-500 mb-10">Panel de Secretaria Clínica</p>

      {/* Tarjetas */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">

        <DashboardCard
          Icon={Calendar}
          title="Agendar Hora"
          subtitle="Crear citas médicas"
          buttonText="Agendar"
          to="/secretaria/agendar"
        />

        <DashboardCard
          Icon={Users}
          title="Pacientes"
          subtitle="Ver y editar pacientes"
          buttonText="Ver Pacientes"
          to="/secretaria/pacientes"
        />

        <DashboardCard
          Icon={UserPlus}
          title="Registrar Paciente"
          subtitle="Agregar un nuevo paciente"
          buttonText="Registrar"
          to="/secretaria/registrar"
        />

        <DashboardCard
          Icon={FileText}
          title="Fichas Médicas"
          subtitle="Ver fichas"
          buttonText="Ver Fichas"
          to="/secretaria/fichas"
        />

        <DashboardCard
          Icon={Calendar}
          title="Agenda del Doctor"
          subtitle="Revisar citas del médico"
          buttonText="Ver Agenda"
          to="/secretaria/agenda-doctor"
        />

      </section>
    </main>
  );
};

export default SecretariaPanel;
