// clinica-react/src/pages/secretaria/SecretariaFichaDetalle.jsx
import { useEffect, useState } from "react";
import { ArrowLeft, FileText } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";

const API = "http://127.0.0.1:8000";

const SecretariaFichaDetalle = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [ficha, setFicha] = useState(null);

  useEffect(() => {
    const cargar = async () => {
      try {
        const res = await fetch(`${API}/fichas/${id}/`);
        const data = await res.json();
        setFicha(data);
      } catch (error) {
        alert("No se pudo cargar la ficha médica");
      }
    };

    cargar();
  }, [id]);

  if (!ficha) return <p className="p-6">Cargando ficha...</p>;

  return (
    <div className="min-h-screen bg-amber-50/60 p-6">

      <button
        onClick={() => navigate("/secretaria/fichas")}
        className="flex items-center text-stone-600 hover:text-stone-900 gap-2 mb-6"
      >
        <ArrowLeft size={20} /> Volver
      </button>

      <div className="bg-white p-8 rounded-3xl border border-amber-100 max-w-3xl mx-auto">
        <h1 className="text-3xl font-semibold flex items-center gap-2 mb-6">
          <FileText className="text-amber-700" /> Ficha Médica
        </h1>

        <div className="space-y-3">
          <p><strong>Paciente:</strong> {ficha.nombre_paciente} {ficha.apellido_paciente}</p>
          <p><strong>RUT:</strong> {ficha.rut_paciente}</p>
          <p><strong>Teléfono:</strong> {ficha.telefono_paciente}</p>
          <p><strong>Dirección:</strong> {ficha.direccion_paciente}</p>
          <p><strong>Previsión:</strong> {ficha.prevision_paciente}</p>

          <p><strong>Título:</strong> {ficha.titulo}</p>
          <p><strong>Notas:</strong> {ficha.notas}</p>

          <p>
            <strong>Fecha:</strong>{" "}
            {new Date(ficha.hora_ficha).toLocaleString("es-CL")}
          </p>
        </div>
      </div>
    </div>
  );
};

export default SecretariaFichaDetalle;

// frontend-consulta/src/app/pages/secretaria/ficha-detalle/secretaria-ficha-detalle.component.ts
import { Component, OnInit } from '@angular/core';
import { NgIf } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-secretaria-ficha-detalle',
  standalone: true,
  imports: [NgIf],
  templateUrl: './secretaria-ficha-detalle.component.html',
})
export class SecretariaFichaDetalleComponent implements OnInit {
  id = '';
  ficha: any = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService
  ) {}

  ngOnInit() {
    this.id = this.route.snapshot.paramMap.get('id') ?? '';
    this.cargar();
  }

  volver() {
    this.router.navigateByUrl('/secretaria/fichas');
  }

  async cargar() {
    try {
      this.ficha = await firstValueFrom(this.api.ficha(this.id));
    } catch {
      alert('No se pudo cargar la ficha.');
      this.ficha = null;
    }
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" class="text-stone-600 hover:text-stone-900 mb-4" type="button">← Volver</button>

  <p *ngIf="!ficha" class="text-stone-600">Cargando ficha...</p>

  <div *ngIf="ficha" class="bg-white border border-amber-100 rounded-3xl p-8 max-w-3xl mx-auto">
    <h1 class="text-3xl font-semibold mb-6">📄 Detalle Ficha</h1>

    <div class="space-y-2 text-stone-800">
      <p><strong>Paciente:</strong> {{ ficha.nombre_paciente }} {{ ficha.apellido_paciente }}</p>
      <p><strong>RUT:</strong> {{ ficha.rut_paciente }}</p>
      <p><strong>Teléfono:</strong> {{ ficha.telefono_paciente }}</p>
      <p><strong>Dirección:</strong> {{ ficha.direccion_paciente }}</p>
      <p><strong>Previsión:</strong> {{ ficha.prevision_paciente }}</p>
      <hr class="my-4" />
      <p><strong>Título:</strong> {{ ficha.titulo }}</p>
      <p><strong>Notas:</strong> {{ ficha.notas }}</p>
      <p><strong>Fecha:</strong> {{ ficha.hora_ficha }}</p>
    </div>
  </div>
</div>
