// frontend-consulta/src/app/pages/user/dashboard/user-dashboard.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-user-dashboard',
  standalone: true,
  templateUrl: './user-dashboard.component.html',
})
export class UserDashboardComponent {
  nombre = localStorage.getItem('userName') || 'Paciente';
  apellido = localStorage.getItem('userApellido') || '';

  constructor(private router: Router) {}

  go(path: string) { this.router.navigateByUrl(path); }
  logout() { localStorage.clear(); this.router.navigateByUrl('/login'); }
}

<main class="min-h-screen bg-amber-50/40 p-6">
  <div class="flex justify-between items-center mb-6">
    <div>
      <h1 class="text-3xl font-semibold">Hola {{ nombre }} {{ apellido }}</h1>
      <p class="text-stone-500">Portal de paciente</p>
    </div>
    <button (click)="logout()" class="px-4 py-2 rounded-xl border" type="button">Cerrar sesión</button>
  </div>

  <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
    <button (click)="go('/user/citas')" class="p-6 bg-white rounded-3xl border text-left" type="button">📅 Mis Citas</button>
    <button (click)="go('/user/agendar')" class="p-6 bg-white rounded-3xl border text-left" type="button">🕒 Agendar Hora</button>
    <button (click)="go('/user/ficha-medica')" class="p-6 bg-white rounded-3xl border text-left" type="button">📄 Mi Ficha</button>
  </div>
</main>

// clinica-react/src/pages/user/UserDashboard.jsx
import DashboardCard from "../../components/common/DashboardCard";
import { Calendar, FileText, Clock, LogOut } from "lucide-react";
import { useNavigate } from "react-router-dom";

const UserDashboard = () => {
  const navigate = useNavigate();

  const nombre = localStorage.getItem("userName") || "Paciente";
  const apellido = localStorage.getItem("userApellido") || "";

  const handleLogout = () => {
    localStorage.clear();
    navigate("/login");
  };

  return (
    <main className="min-h-screen bg-amber-50/40 px-6 py-8">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-semibold text-stone-900">
            Hola {nombre} {apellido}
          </h1>
          <p className="text-stone-500">Bienvenido a tu portal de paciente.</p>
        </div>

        {/* Botón cerrar sesión */}
        <button
          onClick={handleLogout}
          className="flex items-center gap-2 px-4 py-2 rounded-xl border border-stone-300 text-stone-700 hover:bg-stone-100 transition"
        >
          <LogOut size={18} />
          Cerrar sesión
        </button>
      </div>

      {/* Cards */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-10">
        <DashboardCard
          Icon={Calendar}
          title="Mis Citas"
          subtitle="Revisa y cancela tus horas médicas"
          buttonText="Ver Citas"
          to="/user/citas"
        />

        <DashboardCard
          Icon={Clock}
          title="Agendar Hora"
          subtitle="Solicita una nueva hora médica"
          buttonText="Agendar"
          to="/user/agendar"
        />

        <DashboardCard
          Icon={FileText}
          title="Mi Ficha Médica"
          subtitle="Consulta tus diagnósticos médicos"
          buttonText="Ver Ficha"
          to="/user/ficha-medica"
        />
      </section>
    </main>
  );
};

export default UserDashboard;
