// frontend-consulta/src/app/pages/user/agendar/user-agendar-hora.component.ts
import { Component, OnInit } from '@angular/core';
import { NgFor, NgIf, NgClass } from '@angular/common';
import { Router } from '@angular/router';
import { ApiService } from '../../../services/api';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-user-agendar-hora',
  standalone: true,
  imports: [NgFor, NgIf, NgClass],
  templateUrl: './user-agendar-hora.component.html',
})
export class UserAgendarHoraComponent implements OnInit {
  pacienteId = Number(localStorage.getItem('pacienteId') || 0);
  fecha = this.todayChile();
  horas: string[] = [];
  selected = '';
  loading = false;

  constructor(private router: Router, private api: ApiService) {}

  ngOnInit() { this.fetchHoras(); }
  volver() { this.router.navigateByUrl('/user/dashboard'); }

  todayChile(): string {
    return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Santiago' }).format(new Date());
  }

  horaFinal(h: string): string {
    const [hh, mm] = h.split(':').map(Number);
    const d = new Date(); d.setHours(hh, mm + 30, 0, 0);
    return d.toTimeString().slice(0, 5);
  }

  async changeFecha(v: string) {
    this.fecha = v;
    await this.fetchHoras();
  }

  async fetchHoras() {
    this.loading = true;
    try {
      const res = await firstValueFrom(this.api.horasOcupadas(this.fecha));
      const ocupadas = res?.ocupadas ?? [];

      const all: string[] = [];
      for (let h = 8; h < 18; h++) {
        all.push(`${String(h).padStart(2,'0')}:00`);
        all.push(`${String(h).padStart(2,'0')}:30`);
      }
      this.horas = all.filter(x => !ocupadas.includes(`${x}:00`));
      this.selected = '';
    } catch {
      this.horas = [];
    } finally {
      this.loading = false;
    }
  }

  async reservar() {
    if (!this.pacienteId || !this.fecha || !this.selected) return alert('Completa los datos');

    try {
      await firstValueFrom(this.api.agendarHora({
        fecha: this.fecha,
        hora_inicio: this.selected,
        hora_final: this.horaFinal(this.selected),
        paciente_id: this.pacienteId,
      }));
      alert('Hora agendada');
      this.router.navigateByUrl('/user/citas');
    } catch (err: any) {
      alert(err?.error?.detail ?? 'Error agendando');
    }
  }
}

<div class="min-h-screen bg-amber-50/60 p-6">
  <button (click)="volver()" type="button">← Volver</button>
  <h1 class="text-3xl font-semibold my-4">📅 Agendar Hora</h1>

  <input type="date" [value]="fecha" [min]="todayChile()"
    (change)="changeFecha($any($event.target).value)"
    class="px-4 py-2 border rounded-lg mb-4" />

  <p *ngIf="loading">Cargando...</p>

  <div *ngIf="!loading" class="grid grid-cols-2 sm:grid-cols-4 gap-3">
    <button *ngFor="let h of horas" (click)="selected=h"
      [ngClass]="selected===h ? 'bg-amber-600 text-white' : 'bg-white border'"
      class="py-2 rounded-lg" type="button">
      {{ h }}
    </button>
  </div>

  <button (click)="reservar()" [disabled]="!selected"
    class="mt-6 w-full py-3 rounded-xl bg-stone-900 text-white font-semibold disabled:opacity-60" type="button">
    Confirmar Hora
  </button>
</div>

// clinica-react/src/pages/user/UserAgendarHora.jsx
import { useEffect, useState } from "react";
import { ArrowLeft, Calendar } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API = "http://127.0.0.1:8000";

const getTodayYmdChile = () =>
  new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Santiago",
  }).format(new Date());

const calcularHoraFinal = (horaInicio) => {
  const [h, m] = horaInicio.split(":").map(Number);
  const d = new Date();
  d.setHours(h, m + 30);
  return d.toTimeString().slice(0, 5);
};

const UserAgendarHora = () => {
  const navigate = useNavigate();

  const pacienteId = localStorage.getItem("pacienteId");

  const [fecha, setFecha] = useState(getTodayYmdChile());
  const [horasDisponibles, setHorasDisponibles] = useState([]);
  const [horaSeleccionada, setHoraSeleccionada] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!fecha) return;

    const fetchHoras = async () => {
      setLoading(true);
      try {
        const res = await fetch(`${API}/horas-ocupadas/?fecha=${fecha}`);
        if (!res.ok) throw new Error("Error HTTP");

        const data = await res.json();
        const ocupadas = data.ocupadas || [];

        const all = [];
        for (let h = 8; h < 18; h++) {
          all.push(`${String(h).padStart(2, "0")}:00`);
          all.push(`${String(h).padStart(2, "0")}:30`);
        }

        const disponibles = all.filter(
          (h) => !ocupadas.includes(`${h}:00`)
        );

        setHorasDisponibles(disponibles);
        setHoraSeleccionada("");
      } catch (e) {
        console.error("Error cargando horas:", e);
        setHorasDisponibles([]);
      } finally {
        setLoading(false);
      }
    };

    fetchHoras();
  }, [fecha]);

  const reservar = async () => {
    if (!fecha || !horaSeleccionada || !pacienteId) {
      alert("Datos incompletos.");
      return;
    }

    try {
      const res = await fetch(`${API}/horas/agendar/`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fecha,
          hora_inicio: horaSeleccionada,
          hora_final: calcularHoraFinal(horaSeleccionada),
          paciente_id: pacienteId,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        alert(data.detail || "Error al agendar hora.");
        return;
      }

      alert("Hora agendada correctamente.");
      navigate("/user/citas");
    } catch (e) {
      console.error(e);
      alert("No se pudo conectar al servidor.");
    }
  };

  const fechaLegible = new Intl.DateTimeFormat("es-CL", {
    timeZone: "America/Santiago",
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(new Date(`${fecha}T12:00:00`));

  return (
    <div className="min-h-screen bg-amber-50/60 p-6">
      {/* 🔙 VOLVER */}
      <button
        onClick={() => navigate("/user/dashboard")} 
        className="flex items-center gap-2 text-stone-600 hover:text-stone-900 mb-6"
      >
        <ArrowLeft size={20} /> Volver
      </button>

      <h1 className="text-3xl font-semibold text-stone-900 mb-2 flex items-center gap-2">
        <Calendar className="text-amber-700" /> Agendar Hora Médica
      </h1>
      <p className="text-stone-500 mb-6">Fecha seleccionada: {fechaLegible}</p>

      {/* Fecha */}
      <label className="font-medium mb-2 block">Seleccione fecha</label>
      <input
        type="date"
        min={getTodayYmdChile()}
        value={fecha}
        onChange={(e) => setFecha(e.target.value)}
        className="w-full px-4 py-2 border rounded-lg mb-6"
      />

      {/* Horas */}
      <div className="bg-white rounded-2xl shadow p-6 border border-amber-100">
        {loading ? (
          <p className="text-stone-500">Cargando horas disponibles...</p>
        ) : horasDisponibles.length === 0 ? (
          <p className="text-stone-500">
            No hay horas disponibles para esta fecha.
          </p>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {horasDisponibles.map((hora) => (
              <button
                key={hora}
                onClick={() => setHoraSeleccionada(hora)}
                className={`py-2 rounded-lg border transition ${
                  horaSeleccionada === hora
                    ? "bg-amber-600 text-white border-amber-600"
                    : "bg-white text-stone-700 border-stone-300 hover:bg-amber-50"
                }`}
              >
                {hora}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Confirmar */}
      <button
        onClick={reservar}
        disabled={!horaSeleccionada}
        className="mt-6 w-full py-3 rounded-xl bg-stone-900 text-white font-semibold hover:bg-stone-800 disabled:opacity-60"
      >
        Confirmar Hora
      </button>
    </div>
  );
};

export default UserAgendarHora;
